"""empty message

Revision ID: b4e0a0b7df2d
Revises: 323b606bc4cc
Create Date: 2020-05-30 15:08:52.765759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4e0a0b7df2d'
down_revision = '323b606bc4cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('init_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'init_number')
    # ### end Alembic commands ###
